spring.application.name=mobile-management

server.port=8888

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mobiledb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Database management
spring.jpa.hibernate.ddl-auto=create

spring.test.database.replace=none
